### ISSUE TITLE
Fix code scanning alert - Query built from user-controlled sources

### ISSUE THREAD

**Issue by Saideep09** [testorg2-target/source2#1]
Tracking issue for:
- [ ] https://github.com/Saideep11111/source2/security/code-scanning/3

**Comment by o4vzXptx4Z0Q8U8VzWAqKYQ7mHnJsZk1wxgMMUP** [comment]
this is completely for testing purpose and for raising the alerts intentionally

**Comment by o4vzXptx4Z0Q8U8VzWAqKYQ7mHnJsZk1wxgMMUP** [comment]
Fixed
